name: ControlDB Deployment

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display checkout files and folders
        run: Get-ChildItem ${{ github.workspace }} -Recurse

      # No Azure login needed for Fabric SQL when using SPN in the connection string

      - name: Build and Deploy SQL Database
        uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.CONTROLDB_CONNECTIONSTRING }}
          path: ${{ github.workspace }}\elt-framework\ControlDB\ELT\Database.sqlproj
          action: Publish
          arguments: >
            /p:DropPermissionsNotInSource=false
            /p:BlockOnPossibleDataLoss=false
            /p:DropRoleMembersNotInSource=false
            /p:DropObjectsNotInSource=false
            /p:IgnoreColumnOrder=true
            /p:IgnorePermissions=true
            /p:AllowIncompatiblePlatform=true
            /p:ExcludeObjectTypes=Logins;Users
